services:
  postgres-core:
    image: postgres:14
    container_name: postgres-core
    restart: unless-stopped
    environment:
      POSTGRES_USER: core_user
      POSTGRES_PASSWORD: core_password
      TZ: Asia/Yangon
      PGTZ: Asia/Yangon
    ports:
      - "5432:5432"
    volumes:
      - core_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-network

  # postgres-notification:
  #   image: postgres:16
  #   container_name: postgres-notification
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: notification_db
  #     POSTGRES_USER: notification_user
  #     POSTGRES_PASSWORD: notification_password
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - notification_db_data:/var/lib/postgresql/data
  #     - ./db/notification/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   networks:
  #     - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    container_name: keycloak_dev
    command: start-dev --import-realm
    ports:
      - "5000:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-core:5432/keycloak
      KC_DB_USERNAME: core_user
      KC_DB_PASSWORD: core_password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_IMPORT_STRATEGY: OVERWRITE_EXISTING
    networks:
      - backend-network
    depends_on:
      - postgres-core
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json:ro

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - keycloak
      - postgres-core
    networks:
      - backend-network
    extra_hosts:
    - "host.docker.internal:host-gateway"


  # ===============================
  # ELK STACK
  # ===============================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node

      # ===============================
      # DEV MODE (ACTIVE)
      # ===============================
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m

      # ===============================
      # PRODUCTION MODE (COMMENTED)
      # Uncomment these when moving to production
      # ===============================

      # Enable security
      # - xpack.security.enabled=true

      # Set bootstrap password for elastic superuser
      # - ELASTIC_PASSWORD=StrongElasticPassword123

      # Enable TLS for HTTP layer (REQUIRED in real production)
      # - xpack.security.http.ssl.enabled=true
      # - xpack.security.http.ssl.keystore.path=certs/http.p12

      # Enable TLS for transport layer (node-to-node)
      # - xpack.security.transport.ssl.enabled=true

      # Increase memory for production
      # - ES_JAVA_OPTS=-Xms1g -Xmx1g

    ports:
      - "9200:9200"

    volumes:
      - es_data:/usr/share/elasticsearch/data
      # For production TLS certificates
      # - ./certs:/usr/share/elasticsearch/config/certs

    networks:
      - elk


  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.2
    container_name: logstash
    depends_on:
      - elasticsearch

    ports:
      - "6000:5000" 
      - "9600:9600"

    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline

    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m

      # ===============================
      # PRODUCTION OPTION (COMMENTED)
      # ===============================

      # If ES security is enabled, use credentials
      # - ELASTIC_USER=elastic
      # - ELASTIC_PASSWORD=StrongElasticPassword123

    networks:
      - elk


  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    depends_on:
      - elasticsearch

    ports:
      - "5601:5601"

    environment:

      # ===============================
      # DEV MODE (ACTIVE)
      # ===============================
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

      # ===============================
      # PRODUCTION MODE (COMMENTED)
      # ===============================

      # Enable when ES security is enabled
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=StrongElasticPassword123

      # If TLS is enabled in ES
      # - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      # - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate

    networks:
      - elk

volumes:
  core_db_data:
  notification_db_data:
  es_data:

networks:
  backend-network:
    driver: bridge
  elk:
    driver: bridge
