input {
  tcp {
    port => 6000
    codec => json
  }
}

filter {
  mutate {
    add_field => { "environment" => "dev" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-microservices-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
